import '../src/index.css'
import '../src/App.css'
import '../src/components/styles/About.css'
import '../src/components/styles/Career.css'
import '../src/components/styles/Contact.css'
import '../src/components/styles/Cursor.css'
import '../src/components/styles/Landing.css'
import '../src/components/styles/Loading.css'
import '../src/components/styles/Navbar.css'
import '../src/components/styles/SocialIcons.css'
import '../src/components/styles/style.css'
import '../src/components/styles/WhatIDo.css'
import '../src/components/styles/Work.css'
import '../src/components/styles/SkillConstellation.css'
import '../src/components/styles/GlobalBackground.css'
import '../src/components/styles/QuoteSection.css'
import '../src/components/styles/ScrollProgressBar.css'
import '../src/components/styles/SkillMatrix.css'
import '../src/components/styles/Certifications.css'
import '../src/components/styles/TechBlog.css'
import '../src/components/styles/GitHubContributions.css'
export default function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}
